name = "DeduplicateFiles"
uuid = "45cc5580-eac1-45fd-aa49-5aebea7ab828"
authors = ["Per Rutquist <per.rutquist@gmail.com> and contributors"]
version = "0.1.0"

[deps]
CRC = "44b605c4-b955-5f2b-9b6d-d2bd01d3d205"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
